DROP TABLE IF EXISTS TBL_PERSON;
 
CREATE TABLE TBL_PERSON (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  age numeric(10) NOT NULL,
  favourite_colour VARCHAR(50) DEFAULT NULL
);